version: 2
updates:
- package-ecosystem: nuget
  directory: "/Martijn.Extensions.Test"
  schedule:
    interval: weekly
    day: saturday
    timezone: Europe/Amsterdam
  open-pull-requests-limit: 10
  assignees:
  - mjwsteenbergen
